# Generated by Django 4.1 on 2022-09-25 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='quantite',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='panier',
            name='quantite',
            field=models.IntegerField(default=1),
        ),
    ]
