# Generated by Django 4.1 on 2022-10-28 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0002_user_address_user_description_user_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
