# Generated by Django 4.1 on 2022-12-13 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0003_alter_commande_client_remove_commande_menu_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='price',
        ),
    ]
