# Generated by Django 4.1 on 2022-12-13 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0004_remove_commande_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='quantite',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
