# Generated by Django 4.1 on 2022-11-01 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0004_alter_blog_name_alter_blogcategorie_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commande',
            name='payement',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Paypal', 'Paypal')], default='Cash', max_length=200),
        ),
    ]
