# Generated by Django 4.1 on 2022-10-19 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0005_alter_team_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='photo',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='prix',
            new_name='price',
        ),
    ]
