# Generated by Django 4.1 on 2022-12-13 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0005_commande_quantite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
