# Generated by Django 4.1 on 2022-11-01 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0005_commande_price_alter_commande_payement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='quantite',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='menu',
        ),
        migrations.AddField(
            model_name='commande',
            name='menu',
            field=models.ManyToManyField(blank=True, related_name='user_com', to='restaurant_app.menu'),
        ),
    ]
