# Generated by Django 4.1 on 2022-12-13 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0006_alter_commande_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commande_rstaurant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='commande',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commande_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
